package tools

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
)

func PrintErrorAndExit(err error) {
	if err != nil {
		println(err.Error())
		os.Exit(1)
	}
}

func GetBlockSignature(blockNumber uint) (string, error) {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	req, err := http.NewRequest("GET", fmt.Sprintf("https://nodes.wavesnodes.com/blocks/headers/at/%d", blockNumber), nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	data := make(map[string]interface{})
	err = json.Unmarshal(body, &data)
	if err != nil {
		return "", err
	}
	if signature, ok := data["signature"].(string); ok {
		return signature, nil
	}
	return "", errors.New("wrong type")
}
